resolver: lts-16.22

packages:
- .

allow-newer: true

extra-deps:
- postgresql-typed-0.6.1.2
- graphql-0.11.0.0
- mu-graphql-0.4.1.0
- mu-persistent-0.3.1.0
- mu-rpc-0.4.0.1
- mu-schema-0.3.1.1
- primitive-extras-0.8
- primitive-unlifted-0.1.3.0
- stm-containers-1.1.0.4
- stm-hamt-1.2.0.4

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
