resolver: lts-16.12

packages:
- .

allow-newer: true

extra-deps:
- postgresql-typed-0.6.1.2
- mu-schema-0.3.0.0
- mu-rpc-0.3.0.0
- mu-graphql-0.3.0.0
- git: https://github.com/hasura/graphql-parser-hs.git
  commit: 1380495a7b3269b70a7ab3081d745a5f54171a9c
- stm-containers-1.1.0.4
- stm-hamt-1.2.0.4
- primitive-extras-0.8
- primitive-unlifted-0.1.3.0

# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
